/**
 * Catálogo público demo (fotos via placeholder — trocar por CDN real em produção).
 * listingProfile: "venda_direta" | "autonomia" (assistida 3%) | "consultoria" (premium 4% / completa 6%)
 */
(function (global) {
  global.VNPrimeCatalog = [
    {
      id: "demo-1",
      codigo: "VN-2048",
      title: "Apartamento vista panorâmica — Vale do Sereno, Nova Lima",
      neighborhood: "Nova Lima",
      type: "Apartamento",
      price: 4200000,
      status: "Aprovado",
      areaM2: 186,
      quartos: 4,
      suites: 3,
      salas: 2,
      banheiros: 4,
      vagas: 3,
      listingProfile: "consultoria",
      commissionPlan: "6%",
      planLabel: "Venda completa · 6%",
      description:
        "Referência de alto padrão no Vale do Sereno: planta inteligente, living integrado à varanda envidraçada e enquadramento da Serra para dentro do apartamento. Acabamentos importados, automação de iluminação, ar condicionado em todos os ambientes e cozinha com ilha em quartzo. Condomínio com lazer completo — piscina aquecida, fitness, spa, quadra e salão de festas com copa profissional — no perfil de empreendimentos boutique da região de Nova Lima.",
      photos: [
        "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=1200&q=80",
        "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&q=80",
        "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200&q=80",
        "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80",
      ],
    },
    {
      id: "demo-2",
      codigo: "VN-3155",
      title: "Casa em condomínio fechado — Segurança e privacidade",
      neighborhood: "Belvedere",
      type: "Casa",
      price: 6800000,
      status: "Aprovado",
      areaM2: 420,
      quartos: 5,
      suites: 4,
      salas: 3,
      banheiros: 6,
      vagas: 6,
      listingProfile: "consultoria",
      commissionPlan: "6%",
      planLabel: "Venda completa · 6%",
      description:
        "Residência térrea em condomínio de altíssimo padrão, com pé-direito duplo no hall, escritório, home theater e espaço gourmet com churrasqueira e adega climatizada. Piscina com borda infinita, deck em ipê e jardim paisagístico. Suíte master com closet duplo e banheiro com hidro. Segurança 24h, heliponto no condomínio e área de lazer coletiva com quadras e lago ornamental. Documentação em ordem, aceita permuta em imóvel de menor valor.",
      photos: [
        "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1613977257363-707e934c7d2f?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=1200&q=80",
      ],
    },
    {
      id: "demo-3",
      codigo: "VN-4401",
      title: "Cobertura duplex com piscina privativa",
      neighborhood: "Nova Lima",
      type: "Cobertura",
      price: 12500000,
      status: "Aprovado",
      areaM2: 520,
      quartos: 5,
      suites: 5,
      salas: 4,
      banheiros: 7,
      vagas: 8,
      listingProfile: "autonomia",
      commissionPlan: "3%",
      planLabel: "Venda assistida · 3%",
      description:
        "Cobertura linear em dois pavimentos, com elevador privativo e terraço amplo com piscina privativa, ofurô e vista para a serra. Ambientes sociais generosos, adega, espaço fitness e sauna seca. Cozinha com equipamentos de alto padrão e despensa. Projeto de iluminação cênica e automação. Vagas cobertas. Oportunidade rara no segmento ultra-luxo da região metropolitana.",
      photos: [
        "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
      ],
    },
    {
      id: "demo-4",
      codigo: "VN-5122",
      title: "Studio inteligente — Lourdes",
      neighborhood: "Lourdes",
      type: "Apartamento",
      price: 1850000,
      status: "Aprovado",
      areaM2: 48,
      quartos: 1,
      suites: 1,
      salas: 1,
      banheiros: 1,
      vagas: 1,
      listingProfile: "autonomia",
      commissionPlan: "3%",
      planLabel: "Venda assistida · 3%",
      description:
        "Studio de alto padrão, mobiliado com marcenaria sob medida e eletros embutidos. Ideal para investidor ou uso próximo ao trabalho. Prédio boutique com rooftop, coworking e lavanderia compartilhada. Metragem otimizada com cama retrátil e painel multiuso. Documentação livre de ônus.",
      photos: [
        "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80",
        "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80",
      ],
    },
    {
      id: "demo-5",
      codigo: "VN-6290",
      title: "Casa térrea contemporânea — Alphaville",
      neighborhood: "Alphaville",
      type: "Casa",
      price: 8900000,
      status: "Aprovado",
      areaM2: 380,
      quartos: 4,
      suites: 3,
      salas: 2,
      banheiros: 5,
      vagas: 4,
      listingProfile: "consultoria",
      commissionPlan: "4%",
      planLabel: "Venda premium VN Prime · 4%",
      description:
        "Projeto arquitetônico contemporâneo com grandes vãos envidraçados, integração total entre sala e jardim, e piscina com deck úmido. Suítes com piso radiante nos banheiros, closet e persianas automatizadas. Lavabo com pedra natural e iluminação indireta. Produção de mídia profissional VN Prime já realizada — anúncio pronto para visitas qualificadas.",
      photos: [
        "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80",
        "https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1200&q=80",
        "https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=1200&q=80",
      ],
    },
  ];
})(window);
